CONFIGURATION_OPTIONS.md
It seems that LocalStrategy for local storage should be 'ls'.
It is defined here https://github.com/liveintent-berlin/live-connect/blob/master/src/model/storage-strategy.js#L7 as:
```
const StorageStrategy = {
cookie: 'cookie',
localStorage: 'ls',
none: 'none'
}
```
And is used https://github.com/liveintent-berlin/live-connect/blob/master/src/utils/storage.js#L214:
```
if (strEqualsIgnoreCase(storageStrategy, StorageStrategy.localStorage)) {
```
So this is string equality. And the value should be 'ls'
=> No-Ticket Fix type. Rename storage strategy for local storage

package-lock.json, package.json, test-config/wdio.browserstack.conf.js, test/it/helpers/browser.js, test/it/helpers/mock-server.js, test/it/live-connect.spec.js
This PR:
- loads the bundle only once. There's no need to load the rollup bundle from FS every time the tracker is requested
- GZIPs the bundle, to potentially reduce the over the wire transfer between CCI & BS
- introduces retries
- splits the waitUntil into much smaller chunks, speeding up tests, as for cases where `expectedRequests` doesn't match the `server.getHistory().length` doesn't always wait for 4 seconds, but also allows more frequent checks on the condition.
Result: BS tests are down from ~20 mins to ~ 10.
=> Optimizations on browserstack tests

COLLECTOR_PARAMS.md, CONFIGURATION_OPTIONS.md, README.md, cjs/live-connect.js, esm/live-connect.js, src/idex/identity-resolver.js, src/live-connect.js, src/manager/identifiers.js, src/pixel/state.js, test/unit/manager/identifiers.spec.js, test/unit/pixel/state.spec.js
As the feature is already covered by `identifiersToResolve` we can safely remove the provided FPC params from config and stop reading those.
=> RTA-119. Removed the redundant option to provide one's own FPC

test-config/wdio.docker.chrome.conf.js
Going from this [version](https://hub.docker.com/layers/selenium/standalone-chrome/3.141.59-20210713/images/sha256-bc4023992691ab8e2f20297f334fdcddd982928fbd969239b39b3dbc2dfc0657?context=explore) to this [version](https://hub.docker.com/layers/selenium/standalone-chrome/3.141.59-20210729/images/sha256-9943ba9d2a89e984080f5681b390229fb47f7d3bb732e4f440456fc52335bae8?context=explore) of standalone Chrome our tests broke. The reason and solution are described here: https://github.com/SeleniumHQ/docker-selenium/issues/1346. 
AFAICS, we may leave the option there forever, as it does not influence our tests.
=> Add the --disable-gpu option

package-lock.json, rollup-modules.config.js, src/config-validators/remove-invalid-pairs.js, src/initializer.js, src/minimal-live-connect.js, src/pixel/state.js, src/standard-live-connect.js, test/unit/config-validators/remove-invalid-pairs.spec.js, test/unit/minimal-live-connect.spec.js, test/unit/pixel/state.spec.js, test/unit/standard-live-connect.spec.js
Delete distributorId before sending error, to prevent infinite loop
=> Delete distributorId before sending error

package-lock.json, src/manager/decisions.js, src/pixel/fiddler.js, src/utils/url.js, test/unit/utils/url.spec.js
The logs: [here](https://search-streams-production-ggatbwema5ghxbi5aqpcvkcile.us-east-1.es.amazonaws.com/_plugin/kibana/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-4h,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:afb18c50-a95e-11ea-b7d9-89ab4e3c16e1,key:details.trackerVersion,negate:!f,params:(query:v2.5.1),type:phrase),query:(match_phrase:(details.trackerVersion:v2.5.1))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:afb18c50-a95e-11ea-b7d9-89ab4e3c16e1,key:errorDetails.name,negate:!f,params:(query:DecisionsResolve),type:phrase),query:(match_phrase:(errorDetails.name:DecisionsResolve)))),index:afb18c50-a95e-11ea-b7d9-89ab4e3c16e1,interval:auto,query:(language:kuery,query:''),sort:!() …
=> Investigate and fix decode urls in Live-connect

src/pixel/sender.js
There is [this](https://search-streams-production-ggatbwema5ghxbi5aqpcvkcile.us-east-1.es.amazonaws.com/_plugin/kibana/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-4h,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:afb18c50-a95e-11ea-b7d9-89ab4e3c16e1,key:errorDetails.name,negate:!t,params:(query:StrayConfig),type:phrase),query:(match_phrase:(errorDetails.name:StrayConfig))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:afb18c50-a95e-11ea-b7d9-89ab4e3c16e1,key:errorDetails.name,negate:!t,params:(query:LCDuplication),type:phrase),query:(match_phrase:(errorDetails.name:LCDuplication))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:afb18c50-a95e-11ea-b7d9-89ab4e3c16e1,key:erro …
=> Add bakersJson in the error message

CONFIGURATION_OPTIONS.md, README.md, src/initializer.ts, src/minimal-live-connect.ts, src/standard-live-connect.ts, test/unit/minimal-live-connect.spec.ts, test/unit/standard-live-connect.spec.ts
https://liveintent.atlassian.net/browse/CM-714
This PR
- creates LiveConnect instances with a local event bus by default instead of the global bus
- does not attach the created LiveConnect instance to the `window` object if no globalVarName is provided instead of attaching `liQ` by default
Related PRs (both will be updated once this PR is merged):
- https://github.com/LiveIntent/Prebid.js/pull/11
- https://github.com/LiveIntent/liveconnectbuilder/pull/93
This is the follow-up to get rid of the global state handling in LC: https://liveintent.atlassian.net/browse/CM-756
=> CM-714 - Do not attach LC to window if no globalVarName is provided

CONFIGURATION_OPTIONS.md, src/idex.ts, src/pixel/sender.ts, src/types.ts
=> Make timeout for Ajax call configurable

.github/dependabot.yaml
A way to cut on BrowserStack runs
=> Grouping of dependabot PRs

package-lock.json, package.json, rollup/dist.config.mjs, src/cache.ts, src/handlers/storage-handler.ts, src/index.ts, src/initializer.ts, src/internal.ts, src/minimal-live-connect.ts, src/standard-live-connect.ts, src/types.ts, src/typings/window.d.ts, src/utils/wrapping.ts, test/it/helpers/preambled.ts
[CM-944]: https://liveintent.atlassian.net/browse/CM-944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CM-944] Expose internal interfaces

.circleci/config.yml
Switched from machine runner to browserstack runner (which has maxConcurrency: 1)
Removed dynamodb locks
=> feat: move to browserstack runner [DEVOPS-1930]

src/standard-live-connect.ts
Get rid of obsolete cookie clean-up. Bonus: `startsWith` is not supported by older browsers and removing it will solve the issue where these browsers emit an error. 
=> NOISSUE - Get rid of clearIdexCache

test-config/wdio.browserstack.conf.mjs
Chrome < 47 tests timeout. Temporarily bumping min Chrome version to 47. We decided to get rid of IE. This PR also does this. 
=> NOISSUE -Bump Chrome min to 47 and remove IE 11

src/pixel/state.ts, src/types.ts, test/unit/standard-live-connect.spec.ts
We started receiving a large amount of requests with unique domain hashes in the domain user ids. Enabling logging of the used domain to better understand the issue. 
=> NOISSUE - Log cookie domain

src/idex.ts, src/pixel/state.ts, src/types.ts, test/unit/idex/identity-resolver.spec.ts, test/unit/standard-live-connect.spec.ts
The domain will be used for filtering on the backend. The idea is to filter out bad 1st party cookies.
Related PRs:
- https://github.com/LiveIntent/live-connect/pull/285
=> NOISSUE - Send cookie domain to idres

src/initializer.ts
`process.env` is used in Prebid, it is not something we have in our build set up. 
=> CM-1083: Drop process env reference

package-lock.json, package.json
There is a [published](https://www.npmjs.com/package/live-connect-js) version 6.3.3 that isn’t in the release/tag in github (the latest on is 6.3.2), when trying to release a new version there was [this](https://app.circleci.com/pipelines/github/LiveIntent/live-connect/2824/workflows/0eb1d6d8-95a7-4ef1-8b6a-24ff886d5f7c/jobs/5607) error:
```
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/live-connect-js - You cannot publish over the previously published versions: 6.3.3.
```
I will increment the version to be able to release a new version
=> No-Ticket: Increment version

package-lock.json, package.json, src/events/error-pixel.ts, src/handlers/call-handler.ts, src/idex.ts, src/pixel/fiddler.ts, src/pixel/sender.ts, src/pixel/state.ts, src/standard-live-connect.ts, src/types.ts, test/unit/events/error-pixel.spec.ts, test/unit/idex/identity-resolver.spec.ts, test/unit/pixel/fiddler.spec.ts, test/unit/pixel/sender.spec.ts, test/unit/pixel/state.spec.ts
[CM-1540]: https://liveintent.atlassian.net/browse/CM-1540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CM-1540] Add support for ip and useragent

COLLECTOR_PARAMS.md, CONFIGURATION_OPTIONS.md
[CM-1546](https://liveintent.atlassian.net/browse/CM-1546)
Add ip addresses info in doc.
[CM-1546]: https://liveintent.atlassian.net/browse/CM-1546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CM-1546 Adjust the doc

src/pixel/state.ts, test-config/wdio.browserstack.conf.js
[CM-1622](https://liveintent.atlassian.net/browse/CM-1622)
[CM-1622]: https://liveintent.atlassian.net/browse/CM-1622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CM-1622 - Do not send X-LI-Provided-User-Agent header if the value is undefined
