- cjs/live-connect.js
- esm/live-connect.js
- package-lock.json
- src/live-connect.js
- test/unit/live-connect.spec.js
In order to track events and potentially build segments out of it, liQ interface was exposed.
> RTA-83. Expose liQ on global window.

- COLLECTOR_PARAMS.md
- CONFIGURATION_OPTIONS.md
- package-lock.json
- package.json
- src/pixel/state.js
- test/unit/pixel/state.spec.js
This PR should allow LC to work in hand with the gdpr flags and values.
> RTA-349. Passing gdpr values along.

- .circleci/config.yml
- COLLECTOR_PARAMS.md
- cjs/live-connect.js
- esm/live-connect.js
- package.json
- src/enrichers/page.js
- src/pixel/state.js
- src/utils/page.js
- test-config/wdio.browserstack.conf.js
- test/it/helpers/browser.js
- test/it/helpers/mock-server.js
- test/it/live-connect.spec.js
- test/unit/enricher/page.spec.js
- test/unit/utils/page.spec.js
https://liveintent.atlassian.net/browse/RTA-286
> RTA-286 Referrer

- .circleci/config.yml
- COLLECTOR_PARAMS.md
- README.md
- test-config/wdio.browserstack.conf.js
- test/it/helpers/browser.js
- test/it/helpers/mock-server.js
- test/it/live-connect.spec.js
[CM-18](https://liveintent.atlassian.net/browse/CM-18)
> Fix tests for referrer

- test-config/wdio.browserstack.conf.js
- test/it/helpers/browser.js
> CM-75: update timeout for tests

- cjs/initializer.js
- cjs/standard-live-connect.js
- esm/initializer.js
- esm/standard-live-connect.js
- src/handlers/storage-handler.js
- test-config/wdio.browserstack.conf.js
The `Object.assign` doesn't exist in IE.
> Uncomment tests. No Object.assign

- test/it/helpers/browser.js
- test/shared/utils/storage.js
> [No ticket] Try using hardcoded ls probe key

- cjs/initializer.js
- cjs/minimal-live-connect.js
- cjs/standard-live-connect.js
- esm/initializer.js
- esm/minimal-live-connect.js
- esm/standard-live-connect.js
- package-lock.json
- src/utils/types.js
- test/unit/idex/identity-resolver-nocache.spec.js
- test/unit/idex/identity-resolver.spec.js
[Ticket link](https://liveintent.atlassian.net/browse/CM-446)
> CM-446: Update the way additional attributes are serialized for idx endpoint

- test/unit/idex/identity-resolver-nocache.spec.js
- test/unit/idex/identity-resolver.spec.js
> Add tests for attaching publisher id to identity resolution requests

- CONFIGURATION_OPTIONS.md
> [NO TICKET] - Fix example for identityResolutionConfig.publisherId

- .circleci/config.yml
- package.json
Relevant docs here: https://github.com/release-it/release-it/blob/master/docs/pre-releases.md
> [No ticket] Allow triggering prereleases

- src/idex/common.js
- test/unit/idex/identity-resolver.spec.js
https://liveintent.atlassian.net/browse/CM-587
> [CM-586] Consider expires header when caching idres responses

- src/idex/common.js
- test/unit/idex/identity-resolver.spec.js
> Add distributorId to the identity resolver url

- .circleci/config.yml
- .gitignore
[CM-669](https://liveintent.atlassian.net/browse/CM-669)
[CM-669]: https://liveintent.atlassian.net/browse/CM-669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CM-669] Allow publishing non major versions from additional branches

- package-lock.json
- package.json
> [No Ticket] Fix deps

- test-config/wdio.browserstack.conf.js
> [CM-717] Switch Google Nexus device for browserstack

- test-config/wdio.browserstack.conf.js
[CM-717](https://liveintent.atlassian.net/browse/CM-717)
Backport of #106 for v3.x branch.
[CM-717]: https://liveintent.atlassian.net/browse/CM-717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CM-717] Browserstack device changes

- src/pixel/sender.ts
> [No Ticket] Fix utcMillis implementation

- src/manager/decisions.ts
- test/unit/events/error-pixel.spec.ts
- test/unit/idex/identity-resolver.spec.ts
- test/unit/manager/decisions.spec.ts
- test/unit/test-utils/with-resources.ts
https://liveintent.atlassian.net/browse/CM-838
> CM-838 - Collect As Many Decision IDs As Possible

- .circleci/config.yml
There no need to daily build the v3 branch.
> NO ISSUE - Remove daily v3 builds

- test-config/wdio.browserstack.conf.js
- test/it/helpers/browser.ts
- test/it/helpers/mock-server.ts
- test/it/live-connect.spec.ts
> CM-921: Improving BS tests

- src/idex.ts
- src/standard-live-connect.ts
> [No Ticket] Nuke idex cache

- COLLECTOR_PARAMS.md
- CONFIGURATION_OPTIONS.md
- package-lock.json
- package.json
- src/idex.ts
- src/pixel/state.ts
- src/types.ts
- test/unit/idex/identity-resolver-nocache.spec.ts
- test/unit/idex/identity-resolver.spec.ts
- test/unit/pixel/state.spec.ts
Ticket: https://liveintent.atlassian.net/browse/CM-982
Related PRs:
- https://github.com/LiveIntent/liveconnectbuilder/pull/215
> CM-982 - Add GPP fields to config

- package-lock.json
- src/handlers/call-handler.ts
- src/pixel/sender.ts
- test/unit/pixel/sender.spec.ts
#[CM-1013](https://liveintent.atlassian.net/browse/CM-1013)
[CM-1013]: https://liveintent.atlassian.net/browse/CM-1013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CM-1013] Retry ajaxgets

- src/enrichers/privacy-config.ts
- test/unit/enricher/privacy-config.spec.ts
[CM-1026]: https://liveintent.atlassian.net/browse/CM-1026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CM-1026] Respect gpp eu section

- src/idex.ts
- src/pixel/state.ts
- test/unit/events/error-pixel.spec.ts
- test/unit/events/event-bus.spec.ts
- test/unit/idex/identity-resolver.spec.ts
- test/unit/minimal-live-connect.spec.ts
- test/unit/pixel/state.spec.ts
[CM-1105]: https://liveintent.atlassian.net/browse/CM-1105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CM-1105] Send provided idcookie to our backend

- COLLECTOR_PARAMS.md
- CONFIGURATION_OPTIONS.md
- src/enrichers/idcookie.ts
- src/idex.ts
- src/pixel/state.ts
- src/types.ts
- src/utils/params.ts
- src/utils/url.ts
- test/unit/enricher/idcookie.spec.ts
- test/unit/events/error-pixel.spec.ts
- test/unit/idex/identity-resolver.spec.ts
- test/unit/pixel/state.spec.ts
Working with the previous design ended up being very annoying as you ended up needing to check the mode everywhere.
> [CM-1105] Refactor how idCookie is stored in the state

- src/pixel/state.ts
- src/utils/query.ts
- test/unit/idex/identity-resolver.spec.ts
- test/unit/pixel/state.spec.ts
[CM-1155]: https://liveintent.atlassian.net/browse/CM-1155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CM-1155] Send raw idcookie

- package-lock.json
- package.json
- rollup/dist.config.js
https://liveintent.atlassian.net/browse/CM-1203
> [CM-1203] Drop mjs-entry plugin

- package-lock.json
- package.json
- rollup/dist.config.js
- rollup/prebid.babel.config.json
- rollup/test-resources.config.js
- test-config/wdio.browserstack.conf.js
- tsconfig.json
> [No Ticket] Prebid specific build
